version: "3.9"
services:
  db:
    container_name: positions_microsservice_db
    image: postgres:14.6
    restart: always
    volumes:
      - /opt/db-data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - app-network
    profiles: ["default", "local"]
  db-test:
    container_name: positions_microservice_db_test
    image: postgres:14.6
    restart: always
    volumes:
      - /opt/db-test-data
    environment:
      - POSTGRES_DB=postgres_test
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
    ports:
      - 5433:5432
    expose:
      - 5432
    networks:
      - app-network
    profiles: ["test"]
  app:
    container_name: app
    depends_on:
      - db
    build: .
    restart: on-failure
    ports:
      - 6868:8080
    environment:
      - JDBC_URL=jdbc:postgresql://db:5431/postgresql
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - app-network
    profiles: ["default"]
  pub_sub_emulator:
    container_name: pub_sub_emulator
    image: thekevjames/gcloud-pubsub-emulator:422.0.0
    restart: always
    ports:
      - 8681:8681
    environment:
      - PUBSUB_PROJECT1=PROJECT_TEST_ID,curriculum-authorization:curriculum-authorization-sub
    expose:
      - 8681
    profiles: ["test"]

networks:
  app-network:
